
# https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/#requirements
# https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises
- name: Install Calico Network
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/{{ calico_version }}/manifests/calico.yaml

# Install Helm 3.x
- name: Install Helm
  shell: |
    rm -rf /opt/helm
    rm -f /usr/local/bin/helm
    rm -f /usr/local/bin/tiller
    wget https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    mkdir /opt/helm
    tar -xvf helm-v{{ helm_version }}-linux-amd64.tar.gz --strip 1 --directory /opt/helm
    rm helm-v{{ helm_version }}-linux-amd64.tar.gz
    chmod u+x /opt/helm/helm
    ln -s /opt/helm/helm /usr/local/bin/helm

# Install Traefik using Helm
- name: Add Traefik Helm chart repository
  shell: |
    helm repo add traefik https://helm.traefik.io/traefik
    helm repo update


- name: Install Traefik
  shell: |
    helm install traefik traefik/traefik

- name: Add Traefik Dashboard ingress
  template:
    src: traefik-dashboard-ingress-route.yaml.j2
    dest: "{{ install_temp_dir }}/traefik-dashboard-ingress-route.yaml"
    mode: 0644

- name: Wait for traefik to be ready
  pause:
     minutes: 1

- name: service content
  shell: |
    kubectl get svc/traefik -o yaml
  register: temp_service_content

- name: Update Traefik service with clusterIP
  shell: |
    kubectl get svc/traefik -o yaml | sed -e "s/^spec:/spec:\n  externalIPs:\n    - {{ hostvars[groups['master'][0]].ansible_host }}/" | kubectl apply -f -

- name: Install Traefik Ingress Controller
  shell: |
    kubectl apply -f {{ install_temp_dir }}/traefik-dashboard-ingress-route.yaml

# Reference - https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
# Use the following for retrieving a bearer token
#  kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')

- name: Install Dashboard
  shell: |
     kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v{{kube_dashboard_version}}/aio/deploy/alternative.yaml
#     kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v{{kube_dashboard_version}}/aio/deploy/recommended.yaml

- name: Add Dashboard Ingress deployment descriptor
  template:
    src: dashboard-ingress.yaml.j2
    dest: "{{ install_temp_dir }}/dashboard-ingress.yaml"
    mode: 0644

- name: Apply Dashboard Ingress
  shell: |
    kubectl apply -f {{ install_temp_dir }}/dashboard-ingress.yaml
